defaults:
  - _self_
  - task: pt

# Experiment args
mode: "pt"
device: gpu
eval_only: false
predict_only: false
seed: 2137

model:
  # name:
  checkpoint_path: ""
  dropout: 0.0
  random_init: true
  compile: true # Pytorch 2.0

data:
  input_length: 512
  mlm_probability: 0.15
  mean_noise_span_length: 3.0
  # num_workers: 2
  num_workers: 8

optim:
  name: adamwscale
  base_lr: 2e-2
  batch_size: 72 #changed from 144
  # total_steps: 65536
  total_steps: 2778
  epochs: -1 # If it's > 0 it overwrites total_steps
  # warmup_steps: 10000
  warmup_steps: 200
  lr_scheduler: cosine
  weight_decay: 0.0
  grad_clip: 1.0
  grad_acc: 4 #changed from 2
  final_cosine: 1e-5

eval:
  every_steps: 300 # Don't eval
  # steps: 500
  steps: 5

checkpoint:
  every_steps: 3

logging:
  neptune: true
  neptune_creds:
    project: "kavisubramanyan2025/local-byt5-train"
    api_token: ""
    tags: "test_run"
  every_steps: 100
  grad_l2: true
  weights_l2: true

hydra:
  job:
    chdir: True
  run:
    dir: ./logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
